version: "2"

services:

    db:
        image: mysql:5.7
        expose:
            - "3306"
        volumes:
            - ./db:/docker-entrypoint-initdb.d:ro
            - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "abc123"
    admin:
        image: phpmyadmin/phpmyadmin:latest
        links:
           - db:db
        ports:
           - "8081:80"
        environment:
            MYSQL_ROOT_PASSWORD: "abc123"
    app:
        image: jlabusch/moodle-log-migrator
        build: .
        links:
            - db
        volumes:
            - ./lib:/opt/lib:ro
            - ./data:/opt/data
        environment:
            RESTRICT_MODULES: "resource"
            RESTRICT_ACTIONS: "update"
            LOSSY_AUDIT: "yes"
            # DISABLE_AUDIT: "yes"
            